import PDFDocument from 'pdfkit';
import type { ReportJson } from '@/types/database';

/**
 * Generates a PDF buffer from a structured report JSON.
 */
export async function generatePdf(report: ReportJson): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margin: 50,
                info: {
                    Title: `${report.mode === 'startup' ? 'Plan de démarrage' : report.mode === 'portfolio' ? 'Portfolio' : 'Audit de site'} – ${report.sector}`,
                    Author: 'Salon AI',
                },
            });

            const chunks: Buffer[] = [];
            doc.on('data', (chunk: Buffer) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // ─── Header ───────────────────────────────────────────────────────
            doc
                .fontSize(10)
                .fillColor('#888888')
                .text('SALON AI', { align: 'right' })
                .moveDown(0.5);

            // ─── Title ────────────────────────────────────────────────────────
            const modeLabels: Record<string, Record<string, string>> = {
                startup: { fr: 'Plan de Démarrage', en: 'Startup Plan' },
                portfolio: { fr: 'Portfolio', en: 'Portfolio' },
                audit: { fr: 'Audit de Site Web', en: 'Website Audit' },
            };

            const titleText =
                modeLabels[report.mode]?.[report.language] || report.mode;

            doc
                .fontSize(24)
                .fillColor('#1a1a2e')
                .text(titleText, { align: 'left' })
                .moveDown(0.3);

            // ─── Sector subtitle ─────────────────────────────────────────────
            doc
                .fontSize(14)
                .fillColor('#4a4a6a')
                .text(report.sector)
                .moveDown(1);

            // ─── Divider ──────────────────────────────────────────────────────
            doc
                .strokeColor('#e0e0e0')
                .lineWidth(1)
                .moveTo(50, doc.y)
                .lineTo(545, doc.y)
                .stroke()
                .moveDown(1);

            // ─── Summary ──────────────────────────────────────────────────────
            doc
                .fontSize(11)
                .fillColor('#333333')
                .text(report.summary, { lineGap: 4 })
                .moveDown(1.5);

            // ─── Sections ─────────────────────────────────────────────────────
            for (const section of report.sections) {
                // Check page space
                if (doc.y > 700) {
                    doc.addPage();
                }

                // Section title
                doc
                    .fontSize(16)
                    .fillColor('#1a1a2e')
                    .text(section.title)
                    .moveDown(0.5);

                // Bullets
                for (const bullet of section.bullets) {
                    if (doc.y > 720) {
                        doc.addPage();
                    }

                    doc
                        .fontSize(10)
                        .fillColor('#555555')
                        .text(`•  ${bullet}`, {
                            indent: 15,
                            lineGap: 3,
                        });
                }

                doc.moveDown(1);
            }

            // ─── CTA ──────────────────────────────────────────────────────────
            if (report.cta) {
                if (doc.y > 680) {
                    doc.addPage();
                }

                doc.moveDown(1);

                // CTA box
                const ctaY = doc.y;
                doc
                    .roundedRect(50, ctaY, 495, 50, 5)
                    .fill('#1a1a2e');

                doc
                    .fontSize(12)
                    .fillColor('#ffffff')
                    .text(report.cta, 60, ctaY + 17, {
                        width: 475,
                        align: 'center',
                    });

                doc.moveDown(3);
            }

            // ─── Footer ───────────────────────────────────────────────────────
            const footerText =
                report.language === 'fr'
                    ? `Généré par Salon AI – ${new Date().toLocaleDateString('fr-CA')}`
                    : `Generated by Salon AI – ${new Date().toLocaleDateString('en-CA')}`;

            doc
                .fontSize(8)
                .fillColor('#999999')
                .text(footerText, 50, 780, { align: 'center' });

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
}
